version: "3.8"

networks:
  patent_network:

services:
  frontend:
    container_name: patent_check_frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - patent_network

  backend:
    container_name: patent_check_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/patent-check
      HOST: "0.0.0.0"  # Add this to make the backend accessible on all network interfaces
    depends_on:
      - postgres
    networks:
      - patent_network

  postgres:
    image: postgres:15
    container_name: patent_check_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patent-check
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Mount the SQL file
    networks:
      - patent_network

volumes:
  postgres_data:
